from django.shortcuts import render
from django.http import HttpResponse, Http404

# Create your views here.
m_url = ["rando", "prime", "defi", "puzzle", "course"]

m_name = ["Randonnées", "Primes", "Défis", "Puzzles", "Courses"]

m_icon = ["http://i.imgur.com/UyqQ3Z5.png",
		  "http://i.imgur.com/A51dpIP.png",
		  "http://i.imgur.com/LhkhmhT.png",
		  "http://i.imgur.com/4lC2KDK.png",
		  "http://i.imgur.com/NZSTAXy.png",]

def view_missionSelect(request):
	return render(request, 'mission/missionSelect.html', {'missions': zip(m_name, m_url, m_icon)})

def view_mission(request, mission):
	if mission in m_url:
		if (mission == "course"):
			list_mission = list_course
			name = m_name[4]
		elif (mission == "defi"):
			list_mission = list_defi
			name = m_name[2]
		elif (mission == "prime"):
			list_mission = list_prime
			name = m_name[1]
		elif (mission == "puzzle"):
			list_mission = list_puzzle
			name = m_name[3]
		else:
			list_mission = list_rando
			name = m_name[0]
		return render(request, 'mission/mission.html', {'mission': list_mission, 'm_name':name})
	raise Http404

list_puzzle = [
	["Laboratoire de proxémie", ["Terres sauvages de Brisban", "", "[&BPkGAAA=]", "", ["http://i.imgur.com/zpGFPYz.jpg"], ]],
	["Domaine de Langmar", ["Plaines d’Ashford", "", "[&BPgGAAA=]", "", ["http://i.imgur.com/z5JGizB.jpg"], ]],
	["Cache d’Angvar", ["Congères d’Antreneige", "", "[&BP8GAAA=]", "", ["http://i.imgur.com/6BdaLZC.jpg"], ]],
]


list_defi = [
	["Brise-attaque des eaux du Tourment", ["Steppes de la Strie Flamboyante", "", "[&BPsBAAA=]", "", ["http://i.imgur.com/6RXIhCt.jpg"], ]],
	["Stigmatisation et mise à mort", ["Champs de Ruines", "", "[&BEsBAAA=]", "", ["http://i.imgur.com/4YbgoyP.jpg"], ]],
	["De gros problèmes", ["Mont Maelstrom", "", "[&BNICAAA=]", "", ["http://i.imgur.com/Iy4lLT7.jpg"], ]],
	["Sauvetage de ravitaillement", ["Marais de Fer", "", "[&BOoBAAA=]", "", ["http://i.imgur.com/41zkUP7.jpg"], ]],
	["Défendez la sentinelle de la brèche", ["Chutes de la Canopée", "", "[&BEYEAAA=]", "", ["http://i.imgur.com/UZK47Fk.jpg"], ]],
	["Lancer de crabe à Sud-Soleil", ["Crique de Sud-Soleil", "", "[&BNAGAAA=]", "", ["http://i.imgur.com/uFWjmys.jpg"], ]],
]

list_course = [
	["Foulée de l Ourse", ["Passage de Lornar", "", "[&BOkAAAA=]", "", ["http://i.imgur.com/0ETDu4t.jpg"], ]],
	["Poulet en fuite", ["Champs de Ruines", "", "[&BEwBAAA=]", "", ["http://i.imgur.com/8NjwfW3.jpg"], ]],
	["Fugue du crabe", ["Crique du Sud Soleil", "", "[&BNAGAAA=]", "", ["http://i.imgur.com/G80N0HD.jpg"], ]],
	["Terrier du Dévoreur", ["Plateau de Diessa", "", "[&BMkDAAA=]", "", ["http://i.imgur.com/gcyLGct.jpg"], ]],
	["Fuite du loup fantôme", ["Hinterlands Harathis", "", "[&BKUAAAA=]", "", ["http://i.imgur.com/PIMk8LP.jpg"], ]],
	["Course arachnide", ["Falaises de Hantedraguerre", "", "[&BF0CAAA=]", "", ["http://i.imgur.com/S8wNxbk.jpg"], ]],
	["Pagaie quaggan", ["Détroit des gorges glacées", "", "[&BIACAAA=]", "", ["http://i.imgur.com/u7TtGJq.jpg"], ]],
]

list_prime = [
	["\"Adjointe\" Brooke", ["Congères Antreneige ", "", "", "", ["http://i.imgur.com/EhzO7wG.jpg?1"],]],
	["André \"Sauvage\" Douest", ["Crique de sud-soleil ", "", "", "", ["http://i.imgur.com/yyEujzb.jpg?1"],]],
	["Bwiki le Rat de bibiliothèque", ["Passage de Lornar ", "", "", "", ["http://i.imgur.com/u4FOC4Y.jpg"],]],
	["Brekkabek le Skritt", ["Hinterlands Harathis ", "", "", "", ["http://i.imgur.com/lqk8y44.jpg"],]],
	["Chaman Arderus Montée", ["Flambecoeur ", "", "", "", ["http://i.imgur.com/NdlIw51.jpg"],]],
	["Croisée Michèle", ["Marais de Lumillule ", "", "", "", ["http://i.imgur.com/1RRKliB.jpg"],]],
	["Félix Colairik", ["Plateau diessa ", "", "", "", ["http://i.imgur.com/07Fkog2.jpg?1"],]],
	["Komali Micui", ["Mont Maelstrom ", "", "", "", ["http://i.imgur.com/KXX9kiI.jpg"],]],
	["Mayana Imposant", ["Marais de Lumillule  ", "", "", "", ["http://i.imgur.com/HqLRN8S.jpg"],]],
	["Poobadoo", ["Colline de Kessex ", "", "", "", ["http://i.imgur.com/i8lKkFh.jpg"],]],
	["Prisonnier 1411", ["Marais de fer ", "", "", "", ["http://i.imgur.com/SVwrG6C.jpg"],]],
	["6-RUS", ["Chutes de la Canopée ", "", "", "", ["http://i.imgur.com/JbfvXpE.jpg"],]],
	["Sotzz le voyou", ["Champs Gendarran ", "", "", "", ["http://i.imgur.com/ceg8i4R.jpg?1"],]],
	["Tarban le Diplomate", ["Terres sauvages de Brisban ", "", "", "", ["http://i.imgur.com/PEqLFe1.jpg"],]],
	["Teesa la Louche", ["Détroit des gorge glacées ", "", "", "", ["http://i.imgur.com/m0YWBFr.jpg"],]],
	["Trekksa la Rusée", ["Steppes Stries Flamboyantes ", "", "", "", ["http://i.imgur.com/kqpufgM.jpg"],]],
	["Trillia Mylieu", ["Champs de ruines ", "", "", "", ["http://i.imgur.com/6q821J8.jpg"],]],
	["Yanonka, la palefrenière de rats", ["Champs de ruines ", "", "", "", ["http://i.imgur.com/9SFufAk.jpg"],]],
]

tp_prime = [
	"", #"Adjointe" Brooke
	"", #André \"Sauvage\" Douest
	"", #Bwiki le Rat de bibiliothèque
	"", #Brekkabek le Skritt
	"", #Chaman Arderus Montée", "Flambecoeur
	"", #Croisée Michèle", "Marais de Lumillule
	"", #Félix Colairik", "Plateau diessa
	"", #Komali Micui", "Mont Maelstrom
	"", #Mayana Imposant", "Marais de Lumillule
	"", #Poobadoo", "Colline de Kessex
	"", #Prisonnier 1411", "Marais de fer
	"", #6-RUS", "Chutes de la Canopée
	"", #Sotzz le voyou", "Champs Gendarran
	"", #Tarban le Diplomate", "Terres sauvages de Brisban
	"", #Teesa la Louche", "Détroit des gorge glacées
	"", #Trekksa la Rusée", "Steppes Stries Flamboyantes
	"", #Trillia Mylieu", "Champs de ruines
	"", #Yanonka, la palefrenière de rats
]

list_rando = [
	["Alcôve de Courtilleracine", 
		 [ "Le Bosquet", "Point de passage du Spéculateur", "[&BLsEAAA=]", "", ["http://androuw.e-monsite.com/medias/images/gw2-gardenroot-alcove-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-gardenroot-alcove-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-gardenroot-alcove-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-gardenroot-alcove-guild-trek-3.jpg"]]],
	["Alimentation en eau d Orvanic", 
		 [ "Marais de Lumillule", "Point de passage du Goulet de l'Océan", "[&BMkBAAA=]", "Vous devrez prendre le passage de tunnel pour arriver à la cascade supérieure, suivrez les flèches sur la carte.", ["http://androuw.e-monsite.com/medias/images/gw2-orvanic-sourcewaters-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-orvanic-sourcewaters-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-orvanic-sourcewaters-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-orvanic-sourcewaters-guild-trek-3.jpg"]]],
	["Antre cachécailleux", 
		 [ "Plaines d'Ashford", "Point de passage de Feritas", "[&BJcDAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-skalestash-hideaway-guild-trek1.jpg", "http://www.lebusmagique.fr/medias/images/gw2-skalestash-hideaway-guild-trek-3.jpg", "http://www.lebusmagique.fr/medias/images/gw2-skalestash-hideaway-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-skalestash-hideaway-guild-trek-4.jpg"]]],
	["Antre de Hurleneige", 
		 [ "Congères d'Antreneige", "Point de passage de la Terrasse du Faucon des neiges", "[&BL8AAAA=]", "", ["http://androuw.e-monsite.com/medias/images/gw2-snowhowl-den-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-snowhowl-den-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-snowhowl-den-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-snowhowl-den-guild-trek-3.jpg"]]],
	["Autel d Inondesel", 
		 [ "Marais de Lumillule", "Point de passage d'Inondesel", "[&BPkAAAA=]", "", ["http://androuw.e-monsite.com/medias/images/gw2-saltflood-altar-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-saltflood-altar-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-saltflood-altar-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-saltflood-altar-guild-trek-4.jpg"]]],
	["Aveuglement de l Erudit", 
		 [ "Falaises de HanteDraguerre", "Point de passage de la Crevasse de Toran", "[&BFwCAAA=]", "", ["http://androuw.e-monsite.com/medias/images/gw2-scholars-blind1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-scholars-blind-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-scholars-blind-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-scholars-blind-guild-trek-2.jpg"]]],
	["Balcon des délices", 
		 [ "Saut de Malchor", "Point de passage de Pagga", "[&BKYCAAA=]", "Le balcon se situe tout en haut au sommet, vous pouvez y accéder via un petit jumping puzzle (il suffit de suivre les points blancs)", ["http://androuw.e-monsite.com/medias/images/gw2-delights-balcony-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-delights-balcony-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-delights-balcony-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-delights-balcony-guild-trek.jpg"]]],
	["Banc de Varech de Malméduse", 
		 [ "Congères d'Antreneige", "Point de passage de l'Exil", "[&BLwAAAA=]", "", ["http://androuw.e-monsite.com/medias/images/gw2-badjelly-kelpbed-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-badjelly-kelpbed-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-badjelly-kelpbed-guild-trek-5.jpg", "http://androuw.e-monsite.com/medias/images/gw2-badjelly-kelpbed-guild-trek-2.jpg"]]],
	["Barrière de Bercebruyère", 
		 [ "Fôret de Caledon", "Point de passage de la Spirale", "[&BDUBAAA=]", "", ["http://androuw.e-monsite.com/medias/images/gw2-briarthorn-barrier-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-briarthorn-barrier-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-briarthorn-barrier-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-briarthorn-barrier-guild-trek.jpg"]]],
	["Belvédère goutedo", 
		 [ "Passage de Lornar", "Point de passage de la Complainte", "[&BOoAAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-steamscrap-overlook-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-steamscrap-overlook-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-steamscrap-overlook-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-steamscrap-overlook-guild-trek-3.jpg"]]],
	["Bistrot rouport", 
		 [ "Citadelle noire", "Point de passage des Terres du rassemblement", "[&BKUDAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-wheelport-pub-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-wheelport-pub-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-wheelport-pub-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-wheelport-pub-guild-trek-3.jpg"]]],
	["Bivouac du Lys", 
		 [ "Montée de Flambecoeur", "Point de passage de la Pointe de glace", "[&BCACAAA=]", "", ["http://androuw.e-monsite.com/medias/images/gw2-lilys-bivvy-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lilys-bivvy-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lilys-bivvy-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lilys-bivvy-guild-trek-4.jpg"]]],
	["Bord de Valaigu", 
		 [ "Les Steppes de la Strie Flamboyante", "Point de passage de Behem", "[&BP0BAAA=]", "", ["http://androuw.e-monsite.com/medias/images/gw2-sharkhollows-edge-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-sharkhollows-edge-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-sharkhollows-edge-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-sharkhollows-edge-guild-trek-3.jpg"]]],
	["Bosquet de Tarstar", 
		 [ "Montée de Flambecoeur", "Point de passage de l'Apostat", "[&BB0CAAA=]", "", ["http://androuw.e-monsite.com/medias/images/gw2-tarstar-copse-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-tarstar-copse-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-tarstar-copse-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-tarstar-copse-guild-trek-3.jpg"]]],
	["Boucherie piègecayeux", 
		 [ "Marais de fer", "Point de passage du Village d'Attrapécaille", "[&BOcBAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-skalecatch-bucher-shop-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-skalecatch-bucher-shop-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-skalecatch-bucher-shop-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-skalecatch-bucher-shop-guild-trek-3.jpg"]]],
	["Cache à miel de Boisecoeur", 
		 [ "Vallée de la Reine", "Point de passage du Camp de Boisecoeur", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-heartwoods-honey-cache-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-heartwoods-honey-cache-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-heartwoods-honey-cache-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-heartwoods-honey-cache-guild-trek-3.jpg"]]],
	["Cache de l Ours des cavernes", 
		 [ "Congères d'Antreneige", "Point de passage de la Terrasse du Faucon des neiges", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-cave-bear-cache-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cave-bear-cache-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cave-bear-cache-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cave-bear-cache-guild-trek-3.jpg"]]],
	["Cache du fugitif", 
		 [ "Rivage Maudit", "Point de passage de Caer Fougère", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-cache-of-the-pursued-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cache-of-the-pursued-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cache-of-the-pursued-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cache-of-the-pursued-guild-trek-3.jpg"]]],
	["Réserve du marchand", 
		 [ "Hoelbrak", "Point de passage de Peeta", "", "Pour atteindre et emplacement, suivez les flèches rouges, vous ne pouvez pas y atteindre du point de passage de la Place du commerce.", ["http://androuw.e-monsite.com/medias/images/gw2-traders-stash-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-traders-stash-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-traders-stash-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-traders-stash-guild-trek-2.jpg"]]],
	["Camp principal du gardien", 
		 [ "Harathi Hinterlands", "Point de passage du Camp de la barricade", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-guardian-overwatch-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-guardian-overwatch-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-guardian-overwatch-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-guardian-overwatch-guild-trek-2.jpg"]]],
	["Canyons de Gallow", 
		 [ "Terres Sauvages de Brisban", "Point de passage des Près de potence", "", "", ["http://androuw.e-monsite.com/medias/images/161731canyonsdegallow.png", "http://androuw.e-monsite.com/medias/images/gw2-toxal-spill-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-toxal-spill-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-toxal-spill-guild-trek-2.jpg"]]],
	["Carré de chou du bandit", 
		 [ "Harathi Hinterlands", "Point de passage de Point de ralliement de Wynchona", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-bandits-cabbage-patch-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-bandits-cabbage-patch-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-bandits-cabbage-patch-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-bandits-cabbage-patch-guild-trek-4.jpg"]]],
	["Cavité de la cathédrale", 
		 [ "Saut de Malchor", "Point de passage de Lyssa", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-cathedrals-cavity1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cathedrals-cavity-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cathedrals-cavity-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cathedrals-cavity-guild-trek-2.jpg"]]],
	["Cavité du Contremaître", 
		 [ "Falaises de HanteDraguerre", "Point de passage de Dociu", "", "Notez que pour arriver à la marque, vous devez sauter sur deux ou trois rampes vu qu'elle est placée au sommet.", ["http://androuw.e-monsite.com/medias/images/gw2-foremans-recess-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-foremans-recess-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-foremans-recess-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-foremans-recess-guild-trek-3.jpg"]]],
	["Cellier de la Garde du Lion", 
		 [ "Contrefort du Voyageur", "Point de passage du Refuge de Doubléperon", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-lionguard-larder-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lionguard-larder-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lionguard-larder-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lionguard-larder-guild-trek-2.jpg"]]],
	["Cellier du Lion Noir", 
		 [ "Le Bosquet", "Point de passage du Spéculateur", "", "Pour avoir accès au cercle d'or en bas, vous devez sauter de la rampe près du marchand du Lion Noir.", ["http://androuw.e-monsite.com/medias/images/gw2-black-lion-root-cellar-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-black-lion-root-cellar-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-black-lion-root-cellar.jpg", "http://androuw.e-monsite.com/medias/images/gw2-black-lion-root-cellar-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-black-lion-root-cellar-guild-trek.jpg"]]],
	["Champ de Montesauvage", 
		 [ "Côte de la Marée Sanglante", "Point de passage Remanda", "", "La zone exacte de l'emplacement de la randonnée de guilde demeure inconnue à ce jour.", ["http://androuw.e-monsite.com/medias/images/gw2-risewild-green1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-risewild-green-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-risewild-green-guild-trek1.jpg"]]],
	["Champ de force de la cinquième brasse", 
		 [ "Détroit de la Dévastation", "Point de passage de la Cloche Vespérale", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-fathom-five-forcefield-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-fathom-five-forcefield-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-fathom-five-forcefield-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-fathom-five-forcefield-guild-trek-4.jpg"]]],
	["Châtiment de Bluup", 
		 [ "Rata Sum", "", "[&BLgEAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-bluups-comeuppance-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-bluups-comeuppance-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-bluups-comeuppance-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-bluups-comeuppance-guild-trek-3.jpg"]]],
	["Chute d East End", 
		 [ "Terres Sauvages de Brisban", "Point de passage d'East End", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-east-end-falls-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-east-end-falls-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-east-end-falls-guild-trek-5.jpg", "http://androuw.e-monsite.com/medias/images/gw2-east-end-falls-guild-trek-2.jpg"]]],
	["Chutes de Gerbécaille", 
		 [ "Chute de la Canopée", "Point de passage d'Okarinoo", "", "L'emplacement du cercle d'or n'est pas encore connu.", ["http://androuw.e-monsite.com/medias/images/gw2-skalesplash-falls-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-skalesplash-falls-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-skalesplash-falls-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-skalesplash-falls-guild-trek-3.jpg"]]],
	["Chutes de la Génitrice", 
		 [ "Détroit des Gorges Glacées", "Point de passage de la Courbe du Yak", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-broodmother-falls-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-broodmother-falls-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-broodmother-falls-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-broodmother-falls-guild-trek-2.jpg"]]],
	["Cisaillement interdit", 
		 [ "Saut de Malchor", "Point de passage des Murmures", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-forbidden-shear-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-forbidden-shear-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-forbidden-shear-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-forbidden-shear-guild-trek-3.jpg"]]],
	["Coeur du flacon du fondateur", 
		 [ "Champs de Ruines", "Point de passage de la Crécerelle", "", "Notez que la marque à activer est dans une des pièces dans le premier étage.", ["http://androuw.e-monsite.com/medias/images/gw2-founders-flagon-hearth-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-founders-flagon-hearth-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-founders-flagon-hearth-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-founders-flagon-hearth-guild-trek-3.jpg"]]],
	["Coffre-fort de Kevach", 
		 [ "Contreforts du Voyageur", "", "[&BMEDAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-kevachs-strongroom-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-kevachs-strongroom-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-kevachs-strongroom-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-kevachs-strongroom-guild-trek-3.jpg"]]],
	["Coin d Anya", 
		 [ "Plateau de Diessa", "Point de passage de Nolan", "", "Vous devez faire un petit puzzle jump pour arriver à cet endroit. Si vous ne trouvez pas, aller voir cette <a href=\"https://www.youtube.com/watch?v=FFNbnMoEMiY\" data-lity>vidéo</a>", ["http://androuw.e-monsite.com/medias/images/gw2-anyas-patch-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-anyas-patch-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-anyas-patch-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-anyas-patch-guild-trek-3.jpg"]]],
	["Coin de Castavall", 
		 [ "Côte de la Marée Sanglante", "Point de passage de Castavall", "", "Du point de passage, ne nagez pas en bas ou en haut. Au lieu de cela, prenez le tunnel qui est parallèle à vous.", ["http://androuw.e-monsite.com/medias/images/gw2-castavall-corner-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-castavall-corner-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-castavall-corner-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-castavall-corner-guild-trek-3.jpg"]]],
	["Coin de Magièdre", 
		 [ "Rata Sum", "Point de passage de la Cour métrique", "", "L'emplacement de cercle d'or est actuellement inconnu.", ["http://androuw.e-monsite.com/medias/images/gw2-magihedron-corner-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-magihedron-corner-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-magihedron-corner-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-magihedron-corner-guild-trek-3.jpg"]]],
	["Col des frères", 
		 [ "Hoelbrak", "Point de passage de la Panthère des neiges", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-brothers-notch-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-brothers-notch-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-brothers-notch-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-brothers-notch-guild-trek-4.jpg"]]],
	["Col du Coeur criant", 
		 [ "Montée de Flambecoeur", "Point de passage de l'Apostat", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-heart-speaks-notch-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-heart-speaks-notch-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-heart-speaks-notch-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-heart-speaks-notch-guild-trek-3.jpg"]]],
	["Console de commande principale LIN39", 
		 [ "Province de Metrica", "", "[&BEcAAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-master-control-lin39-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-master-control-lin39-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-master-control-lin39-guild-trek-3.jpg", "http://www.lebusmagique.fr/medias/images/gw2-master-control-lin39-guild-trek-4.jpg"]]],
	["Contrepoids d Osenfold", 
		 [ "Contrefort du Voyageur", "Point de passage d'Osenfold", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-osenfold-counterweights-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-osenfold-counterweights-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-osenfold-counterweights-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-osenfold-counterweights-guild-trek-2.jpg"]]],
	["Côte de Couvedrake", 
		 [ "Plateau de Diessa", "Point de passage Brèchezeaux", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-drakehatch-shore-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-drakehatch-shore-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-drakehatch-shore-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-drakehatch-shore-guild-trek-3.jpg"]]],
	["Côte de Togatl", 
		 [ "Collines de Kesse", "Point de passage de Viathan", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-tagotl-shore-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-tagotl-shore-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-tagotl-shore-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-tagotl-shore-guild-trek-3.jpg"]]],
	["Cour de Chutes brisées", 
		 [ "Citadelle Noire", "Point de passage des Ruines de Rin", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-broken-falls-courtyard-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-broken-falls-courtyard-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-broken-falls-courtyard-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-broken-falls-courtyard-guild-trek-3.jpg"]]],
	["Cour des Chutes de la Biche", 
		 [ "Plaines d'Ashford", "Point de passage de la Cité d'Ascalon", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-doefalls-court-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-doefalls-court-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-doefalls-court-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-doefalls-court-guild-trek-3.jpg"]]],
	["Crevasse du Gibier", 
		 [ "Passage de Lornar", "Point de passage de la Maison de Vangir", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-venison-hollow-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-venison-hollow-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-venison-hollow-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-venison-hollow-guild-trek-2.jpg"]]],
	["Crique d Isenfell", 
		 [ "Congères d'Antreneige", "", "[&BLgAAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-isenfell-wash-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-isenfell-wash-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-isenfell-wash-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-isenfell-wash-guild-trek-3.jpg"]]],
	["Crique de Trouvécaille", 
		 [ "Montée de Flambecoeur", "Point de passage du Poste de Commandement de Tuyere", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-skalefound-cove-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-skalefound-cove-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-skalefound-cove-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-skalefound-cove-guild-trek-2.jpg"]]],
	["Débarras d Ulta", 
		 [ "Terres Sauvages de Brisban", "Point de passage de la Métamagique d'Ulta", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-ulta-scraproom-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ulta-scraproom-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ulta-scraproom-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ulta-scraproom-guild-trek-2.jpg"]]],
	["Dents de la corruption", 
		 [ "Détroit des Gorges Glacées", "Point de passage de Drakkar", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-corruptions-teeth-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-corruptions-teeth-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-corruptions-teeth-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-corruptions-teeth-guild-trek-3.jpg"]]],
	["Désir de Pochtecatl", 
		 [ "Côte de la marée sanglante", "", "[&BK8BAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-pochtecatls-desire-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-pochtecatls-desire-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-pochtecatls-desire-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-pochtecatls-desire-guild-trek-3.jpg"]]],
	["Déversoir de Thaumanova", 
		 [ "Province de Metrica", "Point de passage muridienne", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-thaumanova-spillway-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-thaumanova-spillway-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-thaumanova-spillway-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-thaumanova-spillway-guild-trek-3.jpg"]]],
	["Distillerie de la Chouette cachée", 
		 [ "Congères d'Antreneige", "Point de passage du Hibou", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-hidden-owl-distillery-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-hidden-owl-distillery-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-hidden-owl-distillery-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-hidden-owl-distillery-guild-trek-4.jpg"]]],
	["Dortoir du Hall de Skibo", 
		 [ "Rata Sum", "Point de passage auxiliaire", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-skibo-hall-dormitory-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-skibo-hall-dormitory-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-skibo-hall-dormitory-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-skibo-hall-dormitory-guild-trek-3.jpg"]]],
	["Échafaudage autoporteur", 
		 [ "Citadelle Noire", "Point de passage des Ruines de Rin", "", "Notez que le cercle d'or est placé au-dessus d'une sorte d'échafaudage sur lequel vous pouvez grimper.", ["http://androuw.e-monsite.com/medias/images/gw2-freestand-scaffold-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-freestand-scaffold-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-freestand-scaffold-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-freestand-scaffold-guild-trek-2.jpg"]]],
	["Emplacement hanté", 
		 [ "Saut de Malchor", "Point de passage des lumières", "", "Notez que aller à cet emplacement peut être un peu compliqué, regarder la vidéo ci-après pour plus d'infos. Essentiellement, vous devez aller au point de compétence au Nord-Ouest par le temple de Dwayna et faire un certain nombre de sauts de difficultés moyenne. <a href=\"http://youtu.be/3Z7Bda1LYWE\">voir la vidéo</a></span>", ["http://androuw.e-monsite.com/medias/images/gw2-spectrehaunt-socket-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-spectrehaunt-socket-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-spectrehaunt-socket-guild-trek-6.jpg", "http://androuw.e-monsite.com/medias/images/gw2-spectrehaunt-socket-guild-trek-5.jpg"]]],
	["Emprise agitée", 
		 [ "Mont Maelström", "Point de passage de l'Ile du Méandre", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-restless-footings-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-restless-footings-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-restless-footings-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-restless-footings-guild-trek-4.jpg"]]],
	["Ermitage abandonné", 
		 [ "Les Steppes de la Strie Flamboyante", "Point de passage de la Pierre Gardienne", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-vacant-hermitage-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-vacant-hermitage-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-vacant-hermitage-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-vacant-hermitage-guild-trek-2.jpg"]]],
	["Escarpement du pêcheur", 
		 [ "Province de Metrica", "Point de passage de la Vieille Fonderie de Golem", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-fishers-crag-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-fishers-crag-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-fishers-crag-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-fishers-crag-guild-trek-4.jpg"]]],
	["Etreinte de l hymne", 
		 [ "Rivage maudit", "", "[&BOQGAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-anthems-hold-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-anthems-hold-guild-trek-3.jpg", "http://www.lebusmagique.fr/medias/images/gw2-anthems-hold-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-anthems-hold-guild-trek-4.jpg"]]],
	["Excavation profanée", 
		 [ "Collines de Kesse", "Point de passage de Sombreplaie", "", "Le cercle d'or est dans la grotte.", ["http://androuw.e-monsite.com/medias/images/gw2-defiled-delve-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-defiled-delve-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-defiled-delve-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-defiled-delve-guild-trek-3.jpg"]]],
	["Faille de Pouacregriffe", 
		 [ "Marais de Fer", "Point de passage du Lac Pourprenage", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-dirtclaw-cleft-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-dirtclaw-cleft-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-dirtclaw-cleft-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-dirtclaw-cleft-guild-trek-4.jpg"]]],
	["Fière tanière du jaguar", 
		 [ "Province de Metrica", "Point de passage muridienne", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-jaguar-pride-den-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-jaguar-pride-den-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-jaguar-pride-den-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-jaguar-pride-den-guild-trek-3.jpg"]]],
	["Folie de Widd", 
		 [ "Forêt de Caledon", "", "[&BDoBAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-widds-folly-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-widds-folly-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-widds-folly-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-widds-folly-guild-trek-3.jpg"]]],
	["Fontaine de Verdance", 
		 [ "Rivage Maudit", "Point de passage de Verdance", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-verdance-font-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-verdance-font-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-verdance-font-guild-trek-3.jpg"]]],
	["Fontaine des racines cachées", 
		 [ "Le Bosquet", "Point de passage du quartier populaire supérieur", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-backroot-foundtain-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-backroot-fountain-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-backroot-fountain-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-backroot-fountain-guild-trek.jpg"]]],
	["Forage du nid de skelk", 
		 [ "Détroit des Gorges Glacées", "Point de passage du Bourbier de la Mélancolie", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-skelknest-borehole-guild-trek1.jpg", "http://www.lebusmagique.fr/medias/images/gw2-skelknest-borehole-guild-trek-3.jpg", "http://www.lebusmagique.fr/medias/images/gw2-skelknest-borehole-guild-trek-2.jpg"]]],
	["Fosse de Piègetroll", 
		 [ "Passage de Lornar", "Point de passage du Prieuré de Durmand", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-trolltrap-pit-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-trolltrap-pit-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-trolltrap-pit-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-trolltrap-pit-guild-trek-2.jpg"]]],
	["Fosse de la guivre des glaces", 
		 [ "Détroit des Gorges Glacées", "Point de passage de Dimotiki", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-icewurm-trench-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-icewurm-trench-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-icewurm-trench-guild-trek.jpg"]]],
	["Fouilles de Stigmafrappe", 
		 [ "Champs de Ruines", "Point de passage de la Mine d'Hellion", "", "Le cercle d'or est dans une pièce cachée au rez-de-chaussée du puzzle jump de la Mine stigmatisé.", ["http://androuw.e-monsite.com/medias/images/gw2-brandstrike-dig-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-brandstrike-dig-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-brandstrike-dig-guild-trek-3.jpg"]]],
	["Fouilleur de fumier", 
		 [ "Falaises de HanteDraguerre", "Point de passage de Steelbrachen", "", "Notez que l'entrée de la Mine de Dissun est localisée par la flèche rouge.", ["http://androuw.e-monsite.com/medias/images/gw2-foragers-midden-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-foragers-midden-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-foragers-midden-guild-trek-3.jpg"]]],
	["Foyer de Kari", 
		 [ "Collines de Kesse", "Point de passage de Cereboth", "", "Il y a un trou dans le sol dans lequel on peut sauter pour accéder au Point chaud de Kari.", ["http://androuw.e-monsite.com/medias/images/gw2-karis-hot-spot-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-karis-hot-spot-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-karis-hot-spot-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-karis-hot-spot-guild-trek-3.jpg"]]],
	["Frayère des drakes des récifs", 
		 [ "Crique de Sud-Soleil", "", "[&BNUGAAA=]", "", ["http://www.lebusmagique.fr/medias/images/", "http://www.lebusmagique.fr/medias/images/", "http://www.lebusmagique.fr/medias/images/gw2-reef-drake-den-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-reef-drake-den-guild-trek.jpg"]]],
	["Fuite de Toxal", 
		 [ "Terres Sauvages de Brisban", "Point de passage de Mirkrise", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-toxal-spill-guild-trek-5.jpg", "http://androuw.e-monsite.com/medias/images/gw2-toxal-spill-guild-trek-8.jpg", "http://androuw.e-monsite.com/medias/images/gw2-toxal-spill-guild-trek-6.jpg", "http://androuw.e-monsite.com/medias/images/gw2-toxal-spill-guild-trek-7.jpg"]]],
	["Galerie du limon de sang", 
		 [ "Côte de la Marée Sanglante", "Point de passage Lugubre", "", "L'obtention du cercle d'or est un peu délicate vu que c'est juste à côté du Limon Champion qui est assez dur à tuer. Une fois que vous êtes à l'intérieur de la caverne, vous devez monter et passer à travers un groupe de morts-vivants avant que vous ne puissiez arriver aux limons.", ["http://androuw.e-monsite.com/medias/images/gw2-blood-ooze-gallery1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-blood-ooze-gallery-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-blood-ooze-gallery-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-blood-ooze-gallery-guild-trek-3.jpg"]]],
	["Geôle de Provatum", 
		 [ "Montée de Flambecoeur", "Point de passage du Gardien", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-provatum-carcer-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-provatum-carcer-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-provatum-carcer-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-provatum-carcer-guild-trek-2.jpg"]]],
	["Gouffre de Whitland", 
		 [ "Mont Maelström", "Point de passage du site du vieux traîneau", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-whitland-sinkhole-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-whitland-sinkhole-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-whitland-sinkhole-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-whitland-sinkhole-guild-trek-4.jpg"]]],
	["Grenier effondré", 
		 [ "Marais de Lumillule", "Point de passage de Fort Cadence", "", "Le cercle d'or est placé au deuxième étage depuis le sommet dans le coin Sud-Est du bâtiment.", ["http://androuw.e-monsite.com/medias/images/gw2-shattered-loft-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-shattered-loft-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-shattered-loft-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-shattered-loft-guild-trek-3.jpg"]]],
	["Griffure de l éclat céleste", 
		 [ "Hinterlands haratis", "Point de passage de Grey Gritta", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-skyshrine-scratch-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-skyshrine-scratch-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-skyshrine-scratch-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-skyshrine-scratch-guild-trek-3.jpg"]]],
	["Griffure invisible", 
		 [ "Fôret de Caledon", "Point de passage de Mabon", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-unseen-scratch-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-unseen-scratch-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-unseen-scratch-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-unseen-scratch-guild-trek-3.jpg"]]],
	["Grotte Oubliée", 
		 [ "Les Steppes de la Strie Flamboyante", "Point de passage de Terra Carorunda", "", "Le cercle d'or se situe au milieu du jumping :", ["http://www.youtube.com/watch?v=86KpGTIS9_Q&feature=share&list=PLZX6gnjnhlb15POrbjew3xWwGJGgz9Yqc"]]],
	["Grotte d Eaudefonte", 
		 [ "Chute de la Canopée", "Point de passage de Banc d'Ecaille", "", "Le cercle d'or est sous l'eau à l'intérieur d'une grotte.", ["http://androuw.e-monsite.com/medias/images/gw2-meltwater-cave-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-meltwater-cave-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-meltwater-cave-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-meltwater-cave-guild-trek-3.jpg"]]],
	["Grotte de Gorgetoile", 
		 [ "Les Steppes de la Strie Flamboyante", "Point de passage du Glaive", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-canyonweb-cave-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-canyonweb-cave-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-canyonweb-cave-guild-trek-3.jpg"]]],
	["Grotte de Lawen", 
		 [ "Champs de Gendarran", "Point de passage du Premier Refuge", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-lawen-grotto-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lawen-grotto-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lawen-grotto-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lawen-grotto-guild-trek-3.jpg"]]],
	["Gué kraalétroi", 
		 [ "Champs de Ruines", "", "[&BE8BAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-narrowkraal-crossing-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-narrowkraal-crossing-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-narrowkraal-crossing-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-narrowkraal-crossing-guild-trek-3.jpg"]]],
	["Guet de la bagarre de barils", 
		 [ "Hoelbrak", "Point de passage de la Boussole du Héros", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-kegbrawl-watch-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-kegbrawl-watch-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-kegbrawl-watch-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-kegbrawl-watch-guild-trek-3.jpg"]]],
	["Guet réverbérant", 
		 [ "Contrefort du Voyageur", "Point de passage d'Écorchenuit", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-reverberants-watch-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-reverberants-watch-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-reverberants-watch-guild-trek-3.jpg"]]],
	["Guivre des sables maraudeuse", 
		 [ "Crique de Sud-Soleil", "", "[&BNUGAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-sandwurm-prowl-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-sandwurm-prowl-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-sandwurm-prowl-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-sandwurm-prowl-guild-trek-3.jpg"]]],
	["Hall de Guilde du Destin", 
		 [ "Vallée de la Reine", "Point de passage de Shaemoor", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-destinys-guildhall-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-destinys-guildhall-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-destinys-guildhall-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-destinys-guildhall-guild-trek-3.jpg"]]],
	["Halte de Coupegorge", 
		 [ "Champs de Gendarran", "Point de passage de Brigantine", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-cutthroats-rest-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cutthroats-rest-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cutthroats-rest-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cutthroats-rest-guild-trek-3.jpg"]]],
	["Halte de Soren Draa", 
		 [ "Province de Metrica", "Point de passage de Soren Draa", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-soren-draa-rest-shop-guild-trek-21.jpg", "http://androuw.e-monsite.com/medias/images/gw2-soren-draa-rest-shop-guild-trek-41.jpg", "http://androuw.e-monsite.com/medias/images/gw2-soren-draa-rest-shop-guild-trek-31.jpg"]]],
	["Impasse du Gladiver", 
		 [ "Rivage Maudit", "Point de passage R&amp;D", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-winterknell-impasse-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-winterknell-impasse-guild-trek-3.jpg"]]],
	["Jardin de Fortepatte", 
		 [ "Plateau de Diessa", "Point de passage de Nageling", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-strongpaws-garden-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-strongpaws-garden-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-strongpaws-garden-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-strongpaws-garden-guild-trek-3.jpg"]]],
	["Laboratoire de la taverne de Turai", 
		 [ "Promontoire Divin", "Point de passage de Balthazar", "", "Il est localisé dans le sous-sol de la taverne.", ["http://androuw.e-monsite.com/medias/images/gw2-turai-tavern-stillroom-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-turai-tavern-stillroom-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-turai-tavern-stillroom-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-turai-tavern-stillroom-5.jpg", "http://androuw.e-monsite.com/medias/images/gw2-turai-tavern-stillroom.jpg"]]],
	["La sellette de Kaldar", 
		 [ "Hoelbrak", "", "[&BI0DAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-kaldars-hot-seat-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-kaldars-hot-seat-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-kaldars-hot-seat-guild-trek-3.jpg", "http://www.lebusmagique.fr/medias/images/gw2-kaldars-hot-seat-guild-trek-4.jpg"]]],
	["Le devoir de Morndottir", 
		 [ "Hoelbrak", "Point de passage du Roche de l'Abris", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-grimdottirs-duty-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-grimdottirs-duty-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-grimdottirs-duty-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-grimdottirs-duty-guild-trek-3.jpg"]]],
	["Le magasin des ouvriers", 
		 [ "Falaises de HanteDraguerre", "Point de passage de la Route Grise", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-the-workers-stores-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-the-workers-stores-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-the-workers-stores-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-the-workers-stores-guild-trek-4.jpg"]]],
	["Les Marches du Talus", 
		 [ "Chute de la Canopée", "Point de passage de Talus", "", "", ["http://www.lebusmagique.fr/medias/images/gw2-talus-steps-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-talus-steps-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-talus-steps-guild-trek-3.jpg"]]],
	["Klub des Karkas", 
		 [ "Crique de Sud-Soleil", "", "[&BNUGAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-the-karka-club-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/", "http://www.lebusmagique.fr/medias/images/gw2-the-karka-club-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-the-karka-club-guild-trek-3.jpg"]]],
	["L impasse du peuple", 
		 [ "Détroit des Gorges Glacées", "Point de passage de Groznev", "", "Pour aller à l'emplacement pour activer le marqueur, vous devez monter sur la rampe supérieure.", ["http://androuw.e-monsite.com/medias/images/gw2-the-peoples-deadlock.jpg", "http://androuw.e-monsite.com/medias/images/gw2-the-peoples-deadlock-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-the-peoples-deadlock-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-the-peoples-deadlock-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-the-peoples-deadlock-5.jpg"]]],
	["Marche vaporeuses", 
		 [ "Crique de Sud-Soleil", "", "[&BNIGAAA=]", "", ["http://www.lebusmagique.fr/medias/images/", "http://www.lebusmagique.fr/medias/images/", "http://www.lebusmagique.fr/medias/images/gw2-steamy-steps-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-steamy-steps-guild-trek-2.jpg"]]],
	["Mirador de Beetletun", 
		 [ "La Vallée de la reine", "", "[&BPoAAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-beetlestone-mirador-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-beetlestone-mirador-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-beetlestone-mirador-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-beetlestone-mirador-guild-trek-3.jpg"]]],
	["Monument à l ancien", 
		 [ "Crique de Sud-Soleil", "", "[&BNgGAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-monument-to-the-ancient-one-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-monument-to-the-ancient-one-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-monument-to-the-ancient-one-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-monument-to-the-ancient-one-guild-trek-3.jpg"]]],
	["Motte de Lamenoire", 
		 [ "Plateau de Diessa", "Point de passage de la Fontaine de Rhand", "", "Atteindre le Cercle d'Or est un peu délicat pour celui ci, vous aurez besoin de marcher le long d'un rebord étroit pour aller au sommet de cette coline.", ["http://androuw.e-monsite.com/medias/images/gw2-blackblade-butte-guild-trek2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-blackblade-butte-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-blackblade-butte-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-blackblade-butte-guild-trek-5.jpg", "http://androuw.e-monsite.com/medias/images/gw2-blackblade-butte-guild-trek-32.jpg"]]],
	["Mouillage de Covington", 
		 [ "Côte de la Marée Sanglante", "Point de passage de la Mouette rieuse", "", "Le cercle d'or est situé tout au fond du bateau de pirate.", ["http://androuw.e-monsite.com/medias/images/gw2-covingtons-stowage-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-covingtons-stowage-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-covingtons-stowage-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-covingtons-stowage-guild-trek-4.jpg"]]],
	["Mouillage du Capitaine", 
		 [ "Saut de Malchor", "Point de passage des lumières", "", "On ne connaît pas encore l'emplacement exacte du cercle d'or. Il pourrait être quelque part sur le bateau submergé.", ["http://androuw.e-monsite.com/medias/images/gw2-captains-berth-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-captains-berth-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-captains-berth-guild-trek-3.jpg"]]],
	["Mur d enceinte de Claypool", 
		 [ "Vallée de la Reine", "Point de passage de Claypool", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-claypool-bailey-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-claypool-bailey-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-claypool-bailey-guild-trek.jpg"]]],
	["Nid d Araignée cavernicole", 
		 [ "Passage de Lornar", "Point de passage de l'Enclave du Pinacle", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-cave-spider-nidus-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cave-spider-nidus-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cave-spider-nidus-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cave-spider-nidus-guild-trek-3.jpg"]]],
	["Nid du raptor", 
		 [ "Marais de Fer", "Point de passage de la Ville de l'Etoile de Caninecol", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-raptors-aerie1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-raptors-aerie-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-raptors-aerie-guild-trek-2.jpg"]]],
	["Objets trouvés de l Autorité du Port", 
		 [ "Rata Sum", "Point de passage du port", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-port-authority-lost-and-found-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-port-authority-lost-and-found-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-port-authority-lost-and-found-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-port-authority-lost-and-found-guild-trek-3.jpg"]]],
	["Oeil du Scorpion des mers", 
		 [ "Rivages Maudits", "Point de passage de la Crête Indiscrête", "", "", ["http://www.lebusmagique.fr/medias/images/gw2-sea-scorpions-eye-guild-trek2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-sea-scorpions-eye-guild-trek-31.jpg", "http://www.lebusmagique.fr/medias/images/gw2-sea-scorpions-eye-guild-trek-5.jpg", "http://www.lebusmagique.fr/medias/images/gw2-sea-scorpions-eye-guild-trek-41.jpg"]]],
	["Œuvre d Heidi", 
		 [ "Hinterlands harathis", "", "[&BKcAAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-heidis-showpiece-guild-trek1.jpg", "http://www.lebusmagique.fr/medias/images/", "http://www.lebusmagique.fr/medias/images/gw2-heidis-showpiece-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-heidis-showpiece-guild-trek-3.jpg"]]],
	["Paddock du moa vert", 
		 [ "Fôret de Caledon", "Point de passage du Refuge de Caledon", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-green-moa-paddock-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-green-moa-paddock-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-green-moa-paddock-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-green-moa-paddock-guild-trek-3.jpg"]]],
	["Palan charmine", 
		 [ "Montée de Flambecoeur", "", "[&BBcCAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-orecart-hoist-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-orecart-hoist-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-orecart-hoist-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-orecart-hoist-guild-trek-3.jpg"]]],
	["Panorama de Phasmatis", 
		 [ "Plaines d'Ashford", "Point de passage du Chantier de Dockfer", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-phasmatis-prospect-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-phasmatis-prospect-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-phasmatis-prospect-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-phasmatis-prospect-guild-trek-4.jpg"]]],
	["Parapet des constellations", 
		 [ "Le Bosquet", "Point de passage quartier populaire supérieur", "", "<span>Notez que le cercle d'or est en réalité à l'extérieur du bâtiment, on accède via une des plates-formes qui s'ouvre à l'extérieur. Du bas du bâtiment, prenez à droite sur la rampe pour avoir accès à une rampe alternative. De cette deuxième rampe, prenez à gauche.</span>", ["http://www.lebusmagique.fr/medias/images/gw2-constellation-parapet1.jpg", "http://www.lebusmagique.fr/medias/images/gw2-constellation-parapet-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-constellation-parapet-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-constellation-parapet-guild-trek-2.jpg"]]],
	["Pas de Tir de Mina", 
		 [ "Promontoire Divin", "Point de passage des Communes", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-minas-target-shoot-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-minas-target-shoot-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-minas-target-shoot-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-minas-target-shoot-guild-trek-4.jpg"]]],
	["Pavillon de Grenth", 
		 [ "Promontoire Divin", "Point de passage de Grenth", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-grenths-pavillion-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-grenths-pavillion-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-grenths-pavillion-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-grenths-pavillion-guild-trek-3.jpg"]]],
	["Pavillon du Seigneur", 
		 [ "Collines de Kesse", "Point de passage du Seigneur", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-overlord-lodge-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-overlord-lodge-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-overlord-lodge-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-overlord-lodge-guild-trek-3.jpg"]]],
	["Perchoir Tubavapeur", 
		 [ "Crique de Sud-Soleil", "", "[&BNUGAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-steampipe-perch-guild-trek-3.jpg", "http://www.lebusmagique.fr/medias/images/", "http://www.lebusmagique.fr/medias/images/gw2-steampipe-perch-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-steampipe-perch-guild-trek-2.jpg"]]],
	["Perchoir de Raptor", 
		 [ "Champs de Gendarran", "Point de passage d'Aveugleneige.", "[&BMwDAAA=]", "", ["http://androuw.e-monsite.com/medias/images/gw2-raptors-perch1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-raptors-perch-4.jpg", "https://i.imgur.com/ERrtcNM.jpg", "https://i.imgur.com/SK57vkG.jpg"]]],
	["Perchoir de l Ermite", 
		 [ "Champs de Ruines", "Point de passage du Campement de Rosko", "", "La zone exacte de l'emplacement de la randonnée de guilde demeure inconnue à ce jour.", ["http://androuw.e-monsite.com/medias/images/gw2-hermits-roost-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-hermits-roost-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-hermits-roost-guild-trek-3.jpg"]]],
	["Perchoir d œil-de-faucon", 
		 [ "Chutes de la Canopée", "", "[&BEUCAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-hawkeye-perch-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-hawkeye-perch-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-hawkeye-perch-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-hawkeye-perch-guild-trek-3.jpg"]]],
	["Pergola d Aubeluit", 
		 [ "Le Bosquet", "Point de passage de Ronan", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-dawngleam-pergola-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-dawngleam-pergola-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-dawngleam-pergola-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-dawngleam-pergola-guild-trek-3.jpg"]]],
	["Pic du Béliervédère", 
		 [ "Falaises de HanteDraguerre", "Point de passage de Travelen", "", "Notez que pour arriver au sommet où est le bélier de Champion, vous devrez monter sur les rochers près de l'emplacement indiqué par les flêches.", ["http://androuw.e-monsite.com/medias/images/gw2-ramview-peak-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ramview-peak-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ramview-peak-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ramview-peak-guild-trek-5.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ramview-peak-guild-trek-41.jpg"]]],
	["Place engloutie", 
		 [ "Détroit de la Dévastation", "Point de passage du Forum Royal", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-drowned-plaza-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-drowned-plaza-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-drowned-plaza-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-drowned-plaza-guild-trek-3.jpg"]]],
	["Plage nécrolithe", 
		 [ "Le Bosquet", "", "[&BBIEAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-necrolith-landing-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-necrolith-landing-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-necrolith-landing-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-necrolith-landing-guild-trek-3.jpg"]]],
	["Planche à dessin de Tekki", 
		 [ "Terres sauvages de Brisban", "", "[&BGUAAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-tekkis-drawing-board-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-tekkis-drawing-board-guild-trek-3.jpg", "http://www.lebusmagique.fr/medias/images/gw2-tekkis-drawing-board-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-tekkis-drawing-board-guild-trek-4.jpg"]]],
	["Plateau de Krallcamden", 
		 [ "Plaines d'Ashford", "Point de passage de la Tour de l'Escarpement", "", "Le cercle d'or est localisé au sommet, on peut y accéder via un petit passage, suivez la ligne inférieur de points blanc sur le screen ci dessous.", ["http://androuw.e-monsite.com/medias/images/gw2-cademkrall-overlook-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cademkrall-overlook-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cademkrall-overlook-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cademkrall-overlook-guild-trek-3.jpg"]]],
	["Plongeur facebourbié", 
		 [ "Mont Maelström", "", "[&BNECAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-deepmire-diver-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-deepmire-diver-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-deepmire-diver-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-deepmire-diver-guild-trek-3.jpg"]]],
	["Poche de diablotin de feu", 
		 [ "Mont Maelström", "Point de passage de Maelstrom", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-flame-imp-pocket-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-flame-imp-pocket-guild-trek-21.jpg", "http://androuw.e-monsite.com/medias/images/gw2-flame-imp-pocket-guild-trek-41.jpg", "http://androuw.e-monsite.com/medias/images/gw2-flame-imp-pocket-guild-trek-31.jpg"]]],
	["Point de vue de Dockfer", 
		 [ "Plaines d'Ashford", "Point de passage du Chantier de Dockfer", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-irondock-viewpoint-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-irondock-viewpoint-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-irondock-viewpoint-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-irondock-viewpoint-guild-trek-3.jpg"]]],
	["Point de vue de Gnashar", 
		 [ "Terres Sauvages de Brisban", "Point de passage de Wendon", "", "Notez que le cercle d'or est placé en haut de la colline accessible via une série de marches en pierres.", ["http://androuw.e-monsite.com/medias/images/gw2-gnashars-viewpoint-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-gnashars-viewpoint-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-gnashars-viewpoint-guild-trek-3.jpg"]]],
	["Point de vue de Rurik", 
		 [ "Promontoire Divin", "Point de passage de Rurikton", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-ruriks-view-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ruriks-view-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ruriks-view-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ruriks-view-guild-trek-4.jpg"]]],
	["Point de vue d isgarren", 
		 [ "Collines de Kesse", "", "[&BBEAAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-isgarren-viewpoint-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-isgarren-viewpoint-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-isgarren-viewpoint-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-isgarren-viewpoint-guild-trek-3.jpg"]]],
	["Pont de Guet-du-feu", 
		 [ "Marais de Fer", "Point de passage du Campement de Guet-du-feu", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-firewatch-flybridge-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-firewatch-flybridge-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-firewatch-flybridge-guild-trek-3.jpg"]]],
	["Porche de Fawcett", 
		 [ "Harathi Hinterlands", "Point de passage d'Arca", "", "Notez que le cercle d'or ne peut être atteint qu'en faisant le Jumping Puzzle <a href=\"https://www.youtube.com/watch?v=FFNbnMoEMiY\">Vengeance de Fawcett</a> entièrement (cliquez sur le nom pour la vidéo faites par la SaDo expédition).", ["http://androuw.e-monsite.com/medias/images/gw2-fawcetts-porch-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-fawcetts-porch-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-fawcetts-porch-guild-trek-31.jpg", "http://androuw.e-monsite.com/medias/images/gw2-fawcetts-porch-guild-trek-5.jpg", "http://androuw.e-monsite.com/medias/images/gw2-fawcetts-porch-guild-trek-41.jpg"]]],
	["Porte de Droknah", 
		 [ "Mont Maelström", "Point de passage du site du vieux traîneau", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-droknahs-gate-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-droknahs-gate-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-droknahs-gate-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-droknahs-gate-guild-trek-2.jpg"]]],
	["Porte de Wikk", 
		 [ "Chute de la Canopée", "Point de passage du Tutorat de Valance", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-wikks-gate-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-wikks-gate-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-wikks-gate-guild-trek-6.jpg"]]],
	["Port extérieur du Vizir", 
		 [ "Détroit de la Dévastation", "Point de passage du Poste Isolé", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-viziers-anteport.jpg", "http://androuw.e-monsite.com/medias/images/gw2-viziers-anteport-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-viziers-anteport-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-viziers-anteport-guild-trek-3.jpg"]]],
	["Portique de Rata Pten", 
		 [ "Mont Maelström", "Point de passage Criterion", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-rata-pten-portico-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-rata-pten-portico-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-rata-pten-portico-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-rata-pten-portico-guild-trek.jpg"]]],
	["Poste de vigie de Décimus", 
		 [ "Plaines d'Ashford", "Point de passage du Point de Garde de Decimus", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-watchpoint-decimus-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-watchpoint-decimus-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-watchpoint-decimus-guild-trek-7.jpg", "http://androuw.e-monsite.com/medias/images/gw2-watchpoint-decimus-guild-trek-6.jpg"]]],
	["Préfecture de Lychcroft", 
		 [ "Collines de Kesse", "Point de passage du Site d'Ombrecoeur", "", "Le cercle d'or est au sommet de la rampe, directement à côté du PNJ de coeur.", ["http://androuw.e-monsite.com/medias/images/gw2-lychcroft-wardenship-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lychcroft-wardenship-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lychcroft-wardenship-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lychcroft-wardenship-guild-trek-3.jpg"]]],
	["Prison de Taupvaquie", 
		 [ "Contrefort du Voyageur", "Point de passage d'Halvaunt", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-moleberia-prison-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-moleberia-prison-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-moleberia-prison-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-moleberia-prison-guild-trek-3.jpg"]]],
	["Promontoire de Portmatt", 
		 [ "Côte de la Marée Sanglante", "Point de passage des Lamentations", "", "Le cercle d'or tout en haut du puzzle jump du Laboratoire du Professeur Portmatt près du coffre. Vous devez entrer dans l'ordre correct 14.xx.xx-49.xx-0.02xx dans le terminal pour arriver à la fin du puzzle. <a href=\"http://www.youtube.com/watch?v=gSnC10GJBI0\">Vidéo du Laboratoire du Professeur Portmatt</a></span>", ["http://androuw.e-monsite.com/medias/images/gw2-portmatts-promontory-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-portmatts-promontory-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-portmatts-promontory-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-portmatts-promontory-guild-trek-2.jpg"]]],
	["Quai de Lestepied", 
		 [ "Détroit de la Dévastation", "Point de passage de Tonnecaboche", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-lightfoot-dock-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lightfoot-dock-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lightfoot-dock-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lightfoot-dock-guild-trek-5.jpg"]]],
	["Recoin du Scriptorium", 
		 [ "Citadelle Noire", "Point de passage du Factorium", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-scriptorium-nook-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-scriptorium-nook-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-scriptorium-nook-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-scriptorium-nook-guild-trek-2.jpg"]]],
	["Recoin du corbeau", 
		 [ "Hoelbrak", "Point de passage de Corbeau", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-ravens-nook-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ravens-nook-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ravens-nook-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ravens-nook-guild-trek-4.jpg"]]],
	["Recoin lapidaire de Flakk", 
		 [ "Rata Sum", "Point de passage de la Comptabilité", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-flakks-lapidary-nook-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-flakks-lapidary-nook-guild-trek-21.jpg", "http://androuw.e-monsite.com/medias/images/gw2-flakks-lapidary-nook-guild-trek-41.jpg", "http://androuw.e-monsite.com/medias/images/gw2-flakks-lapidary-nook-guild-trek-31.jpg"]]],
	["Refuge d Antreneige", 
		 [ "Congères d'Antreneige", "Point de passage de la Congère", "", "Il y a une entrée à cette petite pièce chambre si vous sautez en bas des murs", ["http://androuw.e-monsite.com/medias/images/gw2-snowden-safehouse-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-snowden-safehouse-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-snowden-safehouse-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-snowden-safehouse-guild-trek-3.jpg"]]],
	["Refuge de siamouth", 
		 [ "Marais de Lumillule", "Point de passage Ondesaline", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-siamoth-refuge-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-siamoth-refuge-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-siamoth-refuge-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-siamoth-refuge-guild-trek-3.jpg"]]],
	["Refuge du Stentor", 
		 [ "Détroit de la Dévastation", "Point de passage du Pic de Signal", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-stentor-shelter-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-stentor-shelter-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-stentor-shelter-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-stentor-shelter-guild-trek-3.jpg"]]],
	["Refuge percebul", 
		 [ "Les Steppes de la Strie flamboyante", "", "[&BFIDAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-burstbubble-blind-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-burstbubble-blind-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-burstbubble-blind-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-burstbubble-blind-guild-trek-3.jpg"]]],
	["Repaire de Soufflettin", 
		 [ "Passage de Lornar", "Point de passage du Gouffre du Démon", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-ettinbreath-lair-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ettinbreath-lair-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ettinbreath-lair-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ettinbreath-lair-guild-trek-3.jpg"]]],
	["Repaire de l Arctodus", 
		 [ "Contrefort du Voyageur", "Point de passage la Colonie de Venbrake", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-arctodus-haunt-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-arctodus-haunt-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-arctodus-haunt-guild-trek-3.jpg"]]],
	["Repère de l Autel du Ruisseau", 
		 [ "Vallée de la Reine", "Point de passage du Carrefour", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-altar-brook-lair-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-altar-brook-lair-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-altar-brook-lair-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-altar-brook-lair-guild-trek-4.jpg"]]],
	["Repli stratégique", 
		 [ "Rivage Maudit", "Point de passage du rocher de l'Epave", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-tactical-retreat-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-tactical-retreat-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-tactical-retreat-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-tactical-retreat-guild-trek-3.jpg"]]],
	["Retraite Gelée", 
		 [ "Chute de la Canopée", "Point de passage Feuilleblanche", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-frozen-antrum-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-frozen-antrum-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-frozen-antrum-guild-trek-5.jpg", "http://androuw.e-monsite.com/medias/images/gw2-frozen-antrum-guild-trek-3.jpg"]]],
	["Rotonde de Soggorsort", 
		 [ "Fôret de Caledon", "Point de passage de l'Escalier du Titan", "", "Le cercle d'or est à l'intérieur d'une des maisons Quaggan.", ["http://androuw.e-monsite.com/medias/images/gw2-soggorsort-rotunda-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-soggorsort-rotunda-guild-trek-21.jpg", "http://androuw.e-monsite.com/medias/images/gw2-soggorsort-rotunda-guild-trek-41.jpg", "http://androuw.e-monsite.com/medias/images/gw2-soggorsort-rotunda-guild-trek-31.jpg"]]],
	["Ruelle du rôdeur de l est", 
		 [ "Promontoire Divin", "Point de passage de Dwayna", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-east-lurk-alley-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-east-lurk-alley-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-east-lurk-alley-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-east-lurk-alley-guild-trek-4.jpg"]]],
	["Salon d Esparvent", 
		 [ "Citadelle Noire", "Point de passage de l'Imperator", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-sparwinds-lounge-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-sparwinds-lounge-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-sparwinds-lounge-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-sparwinds-lounge-guild-trek-2.jpg"]]],
	["Salon de Wrelk", 
		 [ "Champs de Gandarran", "", "[&BJQBAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-wrelks-salon-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/", "http://www.lebusmagique.fr/medias/images/gw2-wrelks-salon-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-wrelks-salon-guild-trek-3.jpg"]]],
	["Sanctuaire hanté par un diablotin", 
		 [ "Fôret de Caledon", "Point de passage du Marais de Wychmire", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-imphaunt-hallow-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-imphaunt-hallow-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-imphaunt-hallow-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-imphaunt-hallow-guild-trek.jpg"]]],
	["Sanctuaire piersacrée", 
		 [ "Plateau de Diessa", "", "[&BMUDAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-holystone-sanctum-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-holystone-sanctum-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-holystone-sanctum-guild-trek-3.jpg", "http://www.lebusmagique.fr/medias/images/gw2-holystone-sanctum-guild-trek-2.jpg"]]],
	["Saut de Drakefaille", 
		 [ "Champs de Ruines", "Point de passage du Guet de Mordrage", "", "Le cercle d'or est placé sur un rocher un peu haut au-dessus du sol. Tourner à gauche après être entré dans la grotte et vous trouverez une petite crevasse avec un rocher au sommet.", ["http://androuw.e-monsite.com/medias/images/gw2-drakecleft-shelf-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-drakecleft-shelf-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-drakecleft-shelf-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-drakecleft-shelf-guild-trek-5.jpg"]]],
	["Saut de Mistriven", 
		 [ "Passage de Lornar", "Point de passage de Mistriven", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-mistriven-shelf-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-mistriven-shelf-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-mistriven-shelf-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-mistriven-shelf-guild-trek-3.jpg"]]],
	["Saut de la conceptualisation", 
		 [ "Rata Sum", "Point de passage de l'incubateur", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-ideation-leap-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ideation-leap-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ideation-leap-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-ideation-leap-guild-trek-3.jpg"]]],
	["Sentinelle Engloutie / Bassin de la Sentinelle", 
		 [ "Marais de Fer", "Point de passage du Campement du Guet du Stigmate", "", "Le cercle d'or est placé à l'intérieur d'une caverne sous-marine accessible en allant au point localisé par la flèche rouge.", ["http://androuw.e-monsite.com/medias/images/gw2-sentinel-sink-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-sentinel-sink-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-sentinel-sink-guild-trek-3.jpg"]]],
	["Sépulcre azumière", 
		 [ "Détroit de la Dévastation", "", "[&BNIEAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-sepulchre-skylight-guild-trek1.jpg", "http://www.lebusmagique.fr/medias/images/", "http://www.lebusmagique.fr/medias/images/gw2-sepulchre-skylight-guild-trek-3.jpg", "http://www.lebusmagique.fr/medias/images/gw2-sepulchre-skylight-guild-trek-2.jpg"]]],
	["Sépulcre ravagé", 
		 [ "Plateau de Diessa", "Point de passage des Landes Ravagées", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-blasted-sepulchre-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-blasted-sepulchre-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-blasted-sepulchre-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-blasted-sepulchre-guild-trek-3.jpg"]]],
	["Seuil d Usharr", 
		 [ "Marais de Lumillule", "", "[&BMsBAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-usharrs-threshold-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-usharrs-threshold-guild-trek-3.jpg", "http://www.lebusmagique.fr/medias/images/gw2-usharrs-threshold-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-usharrs-threshold-guild-trek-4.jpg"]]],
	["Sommet de l Epave", 
		 [ "Citadelle Noire", "Point de passage de l'Épave", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-junkers-apex-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-junkers-apex-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-junkers-apex-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-junkers-apex-guild-trek-3.jpg"]]],
	["Source de Brûlereinette", 
		 [ "Marais de Lumillule", "Point de passage de Flamefrog", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-firefrog-springs-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-firefrog-springs-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-firefrog-springs-guild-trek-3.jpg"]]],
	["Source de Melandru", 
		 [ "Le Promontoire divin", "", "[&BCoDAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-dwaynas-fount-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-dwaynas-fount-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-dwaynas-fount-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-dwaynas-fount-guild-trek-3.jpg"]]],
	["Source des lamentations", 
		 [ "Détroit des georges glacées", "", "[&BIECAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-source-of-lament-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-source-of-lament-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-source-of-lament-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-source-of-lament-guild-trek-3.jpg"]]],
	["Surprise d Elise", 
		 [ "Harathi Hinterlands", "Point de passage de Demetra", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-elises-suprise-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-elises-suprise-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-elises-suprise-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-elises-suprise-guild-trek-2.jpg"]]],
	["Surveillant de Folleflamme", 
		 [ "Province de Metrica", "Point de passage de Soren Draa", "", "Notez que la marque est au deuxième étage. Il y a des marches en pierre sur les côtés sur lesquelles vous pouver sauter pour atteindre le sommet.", ["http://androuw.e-monsite.com/medias/images/gw2-wildflame-monitor-guild-trek-2.jpg"]]],
	["Terrasse de Wassa", 
		 [ "Champs de Gendarran", "Point de passage Premier Refuge", "", "Le cercle d'or est placé en haut sur la tour la plus haute.", ["http://androuw.e-monsite.com/medias/images/gw2-wassas-terrace-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-wassas-terrace-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-wassas-terrace-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-wassas-terrace-guild-trek-4.jpg"]]],
	["Tour de guet de Mâchefléau", 
		 [ "Marais de Fer", "Point de passage du Campement de Belpelisse", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-scourgejaw-watchtower-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-scourgejaw-watchtower-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-scourgejaw-watchtower-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-scourgejaw-watchtower-guild-trek-2.jpg"]]],
	["Tour de la tribulation", 
		 [ "Falaises de Hantedraguerre", "", "[&BFYCAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-tower-of-tribulation-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-tower-of-tribulation-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-tower-of-tribulation-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-tower-of-tribulation-guild-trek-3.jpg"]]],
	["Trou de tirailleur de Creusepierre", 
		 [ "Champs de Gendarran", "Point de passage de Talajian", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-stonebore-spiderhole-guild-trek1.jpg", "http://androuw.e-monsite.com/medias/images/gw2-stonebore-spiderhole-guild-trek-21.jpg", "http://androuw.e-monsite.com/medias/images/gw2-stonebore-spiderhole-guild-trek-41.jpg"]]],
	["Tunnel de Bandacier", 
		 [ "Les Steppes de la Strie Flamboyante", "Point de passage de Tumok", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-steelbands-tunnel-guild-trek2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-steelbands-tunnel-guild-trek-22.jpg", "http://androuw.e-monsite.com/medias/images/gw2-steelbands-tunnel-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-steelbands-tunnel-guild-trek-5.jpg"]]],
	["Tunnel sous le lac", 
		 [ "Vallée de la Reine", "Point de passage de la Scierie d'Ojon", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-lakebottom-underpass-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lakebottom-underpass-guild-trek-2.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lakebottom-underpass-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-lakebottom-underpass-guild-trek-3.jpg"]]],
	["Upsilon Hyperboloïde", 
		 [ "Saut de Malchor", "", "[&BKgCAAA=]", "", ["http://www.lebusmagique.fr/medias/images/gw2-upsilon-hyperboloid-guild-trek.jpg", "http://www.lebusmagique.fr/medias/images/gw2-upsilon-hyperboloid-guild-trek-2.jpg", "http://www.lebusmagique.fr/medias/images/gw2-upsilon-hyperboloid-guild-trek-4.jpg", "http://www.lebusmagique.fr/medias/images/gw2-upsilon-hyperboloid-guild-trek-3.jpg"]]],
	["Vallon de Cymbel", 
		 [ "Champs de Ruines", "Point de passage de la Route de l'ogre", "", "", ["http://androuw.e-monsite.com/medias/images/gw2-cymbels-glen-guild-trek.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cymbels-glen-guild-trek-4.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cymbels-glen-guild-trek-3.jpg", "http://androuw.e-monsite.com/medias/images/gw2-cymbels-glen-guild-trek-2.jpg"]]],
]